### ISSUE TITLE
Cannot pass function as argument to Vte

### ISSUE THREAD

**Issue by romgrk** [WebReflection/node-gtk#2]
``` coffee
terminal = new Vte.Terminal
terminal.spawn_sync(
    terminal,
    0, #Vte.PtyFlags.DEFAULT
    __dirname,
    ['/bin/zsh'],
    ( "#{key}=#{process.env[key]}" for key of process.env ),
    4, #GLib.SpawnFlags.SEARCH_PATH
    null, 
)
```

Error code:

```
ERROR:../src/value.cc:180:void GNodeJS::V8ToGIArgument(v8::Isolate*, GITypeInfo*, GIArgument*, v8::Handle<v8::Value>, bo
ol): code should not be reached
[1]    21304 abort      node .
```

Code

``` c
    case GI_TYPE_TAG_INTERFACE:
        {
            GIBaseInfo *interface_info = g_type_info_get_interface (type_info);
            GIInfoType interface_type = g_base_info_get_type (interface_info);

            switch (interface_type) {
            case GI_INFO_TYPE_OBJECT:
                arg->v_pointer = GObjectFromWrapper (value);
                break;
            default:
                g_assert_not_reached ();
            }

            g_base_info_unref (interface_info);
        }
        break;
```

From what I can see there are various unimplemented types. (ref: https://developer.gnome.org/gi/stable/gi-GIBaseInfo.html#GIInfoType)

Are some of them unrelevant to implement or is this todo?

**Comment by magcius** [comment]
Was this originally Ruby code or something? The syntax `( "#{key}=#{process.env[key]}" for key of process.env )` clearly isn't JS.

Could you post what code you used to retrieve the error?

**Comment by magcius** [comment]
Managed to figure this one out. Pushed some fixes which add more cases to the value marshaller, and starts handling some more complex cases in function calling, like GErrors.

It's nowhere near complete, but maybe gets us a bit closer.

**Comment by romgrk** [comment]
Yes! Sorry about the syntax, it's coffeescript.
Compiles to 

``` javascript
var key, ref, val;
ref = process.env;
for (key in ref) {
  val = ref[key];
  key + "=" + val;
}
```

Thanks for looking into this. 
I was reading some doc from gobject-introspection, it shouldnt be so hard to have a working version, no? I have nerver worked with gnome/gtk code. (Oh and their documentation website is hideous)

**Comment by magcius** [comment]
I think this is good now.

**Comment by romgrk** [comment]
No, the specific case isnt resolved yet but I'll do my investigation and I'll update/open another thread with more details.
