### ISSUE TITLE
Error in node-gtk lib, after try run code 

### ISSUE THREAD

**Issue by friktor** [WebReflection/node-gtk#21]
Hi, I tried to use your library, but there was this error.

```
node: symbol lookup error: /home/anton/nodeGtk/node_modules/node-gtk/build/Release/node-gtk.node: undefined symbol: g_irepository_get_default
```

All libraries for the development of gtk installed. The assembly took place without problems. OS - Ubuntu 16.04 Gnome.

**Comment by WebReflection** [comment]
have you tried to `sudo apt-get install npm gjs` first?

**Comment by friktor** [comment]
the main shell is a gnome-shell, so gjs already in the system, and a standard set of nodejs already comes with npm

**Comment by WebReflection** [comment]
I'm on Gnome too. I have node 5, gjs, and if I `npm install` within this repo it works.

**Comment by kidwm** [comment]
have you tried to install `libgirepository1.0-dev` ?

**Comment by marphy-sk** [comment]
I have same problem. 
I installed libgirepository1.0-dev, npm, node 5, gjs, node-gtk, gtk3.  
`node: symbol lookup error: /usr/lib/node_modules/node-gtk/build/Release/node-gtk.node: undefined symbol: g_irepository_get_default
`

**Comment by WebReflection** [comment]
I've just managed to do everything following instructions now published on the readme too.

``` bash
# setup node v5
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -

# install dependencies
sudo apt-get install \
  build-essential \
  git \
  nodejs \
  gobject-introspection \
  libgirepository1.0-dev

# clone and build
git clone https://github.com/WebReflection/node-gtk.git
cd node-gtk
npm install

# how to verify from node-gtk folder
./examples/hello-gtk.js
```

**Comment by marphy-sk** [comment]
It same 
`node: symbol lookup error: $PATH/nodeApp/node-gtk/build/Release/node-gtk.node: undefined symbol: g_irepository_get_default`

**Comment by WebReflection** [comment]
which version of ubuntu?

**Comment by marphy-sk** [comment]
i am using 15.10
Dňa 22.2.2016 4:31 PM používateľ "Andrea Giammarchi" <
notifications@github.com> napísal:

**Comment by WebReflection** [comment]
please `git pull --rebase` and then `npm install` again, it should have been fixed.

Also there are notes for Ubuntu 16 LTS and nodejs 5 installation:
https://github.com/WebReflection/node-gtk#how-to-install-node-5x-in-ubuntu-16-lts

**Comment by marphy-sk** [comment]
Now is success, thenks .. Goog job

**Comment by WebReflection** [comment]
thanks, I'm waiting for @friktor to confirm it works now for him too so that we can close this bug.

**Comment by friktor** [comment]
@WebReflection hi, yes it worked, thanks for the answer

**Comment by friktor** [comment]
@WebReflection While the project is under development, please regularly publish fresh package on npm, when the bug is solved.

**Comment by WebReflection** [comment]
I'm not sure anything will work from npm, which is why I should rather update the README ;-)
