### ISSUE TITLE
First-run fails with missing symbol

### ISSUE THREAD

**Issue by Fordi** [WebReflection/node-gtk#22]
Installed as noted in README.md; running `./examples/hello-gtk.js` results in

```
node: symbol lookup error: /home/rsi-bryan/Personal/node-gtk/build/Release/node-gtk.node: undefined symbol: g_irepository_get_default
```

**Comment by WebReflection** [comment]
I have a fresh new Ubuntu installed on a VM just to try that README instructions and it works without problems.

Please confirm the following points:
- it's Ubuntu 15.10 (latest apt-get update and apt-get dist-upgrade)
- everything described in the README is performed
- node is the version 5 and with latest npm too

Thanks

**Comment by WebReflection** [comment]
please `git pull --rebase` and then `npm install` again, it should have been fixed.

**Comment by magcius** [comment]
Assumed fixed by now.
