### ISSUE TITLE
Boxeds are not publicly exposed yet

### ISSUE THREAD

**Issue by benwaffle** [WebReflection/node-gtk#5]
maybe because in the gir it is a `<record>` and not a `<class>`

**Comment by magcius** [comment]
We don't expose boxeds publicly yet -- they're only supported as internal values. It shouldn't be too hard to add support for boxeds -- see what we do for classes in JS -- but I first want to rework the overrides / JS system so that we run those whenever a module is used, even from within C code.

**Comment by WebReflection** [comment]
I've uploaded a WebKit2 Gtk+ example called [browser.js](https://github.com/WebReflection/node-gtk/blob/master/examples/browser.js) to test more complex scenarios. Everything seems to be OKish but I have two different errors.

The following one is on Linux and I thought it had to do with some not handled boxed value.

```
ERROR:../src/value.cc:268:void GNodeJS::V8ToGValue(GValue*, v8::Handle<v8::Value>): code should not be reached
```

The other one is on OSX, it's about line 35 of `function.cc`, it says that the assertion `value-isArray ()` failed. Not sure why this is happening only on OSX, but I wonder if [latest changes I've pushed for both OSX and Windows](https://github.com/WebReflection/node-gtk/blob/master/src/closure.cc#L35-L49) could be the cause.

Once again, I hope you'll find some little time to move on with the C++ part which I'm afraid I don't know so well. I'm taking care of making this work on OSX and Windows too: I am that close for Windows, and it's already working on OSX beside one gotcha I need to fix with the `PKG_CONFIG_PATH` variable.

**Comment by magcius** [comment]
I implemented something silly for this right now -- I can't double-check that it works, though.

**Comment by romgrk** [comment]
If you'd like to collaborate on this don't hesitate to ask. 
I have implemented this in a very similar fashion (see https://github.com/romgrk/node-gtk/blob/master/src/gi.cc#L182). It gets somewhat painful for caller-allocated boxeds. (And don't get me started on unions). Maybe can I open subject specific PRs?

You might be interested in https://github.com/nodejs/nan.

**Comment by magcius** [comment]
I looked at nan and didn't like the API. That said, I agree that a lot of your changes should probably be reintegrated back here.

**Comment by romgrk** [comment]
I'll look into making some clean PRs. It would also relieve me of some stress having someone examining thoses changes, most of it has been try-error guessing with the GObject API.
