### ISSUE TITLE
Gtk.init(null); throws an error

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/node-gtk#6]
The following code works in `node-gtk` but doesn't in `GJS`

``` js
#!/usr/bin/env node
var
  GNode = require('node-gtk'),
  Gtk = GNode.importNS('Gtk')
;

GNode.startLoop();
Gtk.init(0, null);
```

The GJS version:

``` js
#!/usr/bin/env gjs
imports.gi.Gtk.init(0, null);

// Gjs-WARNING **: JS ERROR: Error: Expected type utf8 for Argument 'argv' but got type 'number'
// @./gjs:2
```

Moreover, if I use just `null` as unique argument, `GJS` works just fine and node-gtk throws an error.

```
Gtk.init(null);
    ^

TypeError: Not enough arguments.
    at TypeError (native)
    at Object.<anonymous> (/home/webreflection/test/gjs/node-gtk:8:5)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

I believe these two way to initialize should be kinda consistent across environment otherwise code might result not shareable/reusable/testable in both envs.

FYI I've also aligned [jsgtk](https://github.com/WebReflection/jsgtk/#jsgtk) to reflect your node-gtk import and API so these can share pretty much exact same code as long as non  native node modules are used. ( [example](https://github.com/WebReflection/jsgtk/blob/master/examples/hello-gtk.js) and it's visible I had to use `Gtk.init(null)` instead of `Gtk.init(0, null)` due previously described error )

**Comment by magcius** [comment]
That's bizarre. I thought I added array length handling in https://github.com/WebReflection/node-gtk/commit/7de374404e4510313f431d2582be1537871a5a80

I'll take a look soon.

**Comment by WebReflection** [comment]
You are actually right. My apologies I thought I was loading latest build while I wasa actually loading the globally installed old one. Nothing to do, this works without problems.

**Comment by romgrk** [comment]
Ha, yeah, I got this one too.
