### ISSUE TITLE
Follow proper enumerability / configurability for GI-defined classes

### ISSUE THREAD

**Issue by magcius** [WebReflection/node-gtk#8]
In #4, @WebReflection points out that class methods and properties are not enumerable, but are configurable.

This should be moderately simple to implement. Basically, patch up `declareFunction` and `makeObject` to follow the proper conventions in https://github.com/WebReflection/node-gtk/blob/master/lib/index.js

**Comment by WebReflection** [comment]
This one I can help. Flying around the world these days, will be back on 7th, will play with the code if I'll find a minute. Feel free to assign to me, I'll create and push a branch for a review.
